### ISSUE TITLE
When an injector is enabled and the service cannot be created, application should crash

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#842]
## Description

When an injector is enabled and the service cannot be created, application should crash.

Currently:

```
2024-05-13T15:03:17.680Z ERROR 7 --- [OpenBAS API] [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

java.lang.RuntimeException: org.apache.hc.client5.http.ClientProtocolException: Unexpected response for request on: http://10.96.3.108/api/v2/agents
        at io.openbas.injectors.caldera.client.CalderaInjectorClient.agents(CalderaInjectorClient.java:66) ~[!/:1.0.0]
        at io.openbas.injectors.caldera.service.CalderaGarbageCollectorService.run(CalderaGarbageCollectorService.java:67) ~[!/:1.0.0]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.1.1.jar!/:6.1.1]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: org.apache.hc.client5.http.ClientProtocolException: Unexpected response for request on: http://10.96.3.108/api/v2/agents
        at io.openbas.injectors.caldera.client.CalderaInjectorClient.get(CalderaInjectorClient.java:191) ~[!/:1.0.0]
        at io.openbas.injectors.caldera.client.CalderaInjectorClient.agents(CalderaInjectorClient.java:62) ~[!/:1.0.0]
        ... 8 common frames omitted

2024-05-13T15:03:17.722Z ERROR 7 --- [OpenBAS API] [           main] i.o.injectors.caldera.CalderaInjector    : Error creating caldera injector
```

With this, even if Caldera is available again, the injector will never work.

**Comment by DeniseMonreale** [comment]
The current behavior is problematic in two ways: the application silently swallows the error and logs it, but the injector is never retried  even if the target service comes back online. The operator has no signal that the injector is broken unless they read the logs.

**Use case:** an operator deploys OpenAEV with Caldera enabled. Caldera is temporarily unreachable at startup (network delay, pod not ready). OpenAEV starts, logs an error, and marks the injector as silently failed. Caldera comes online 2 minutes later  but the injector never reconnects. The operator runs a simulation, injects are dispatched to Caldera, nothing executes. The operator discovers the issue only when reviewing results.

The fix should introduce a **startup validation + retry mechanism**:
- At startup, if an enabled injector's service cannot be created, the application should either crash (fail-fast) or enter a retry loop with a configurable backoff 
- If crash is chosen: the operator is forced to fix the configuration before the platform starts, which prevents silent failures downstream
- If retry is chosen: the injector should be marked as `UNAVAILABLE` in the UI (surfacing the health check introduced in #855) until the service is reachable and the bean is successfully initialized

The fail-fast approach is simpler and more predictable for production deployments. The retry approach is more resilient in dynamic environments (Kubernetes, Docker Compose with dependency ordering)

**Comment by SamuelHassine** [comment]
Re-assessed against current main as part of the legacy bug backlog sweep. The failure mode described (an injector Spring bean failing at boot and never being retried) no longer exists: injectors/executors moved to the integration framework, where ManagerIntegrationsSyncJob re-runs initialise() on every cycle, a failed start leaves the instance stopped with its status persisted and visible in the UI, and start is retried on the next round. Closing as obsolete/superseded.
